
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND APPLY COLON COMMA CREATE EQ FLOAT GATE GE GT IDENT INT LBRACE LBRACKET LE LPAREN LT MEASURE NE ON OR QUBITS RBRACE RBRACKET RPAREN SELECT SEMICOLON STAR WHEREprogram : statement_list\n    statement_list : statement statement_list\n                   | statement\n    \n    statement : create_stmt\n              | apply_stmt\n              | measure_stmt\n              | gate_def\n    create_stmt : CREATE QUBITS IDENT LBRACKET INT RBRACKET SEMICOLON\n    condition_expr : condition_expr AND condition_expr\n                   | condition_expr OR condition_expr\n                   | simple_condition\n    \n    number : INT\n           | FLOAT\n    \n    simple_condition : IDENT LT number\n                     | IDENT GT number\n                     | IDENT LE number\n                     | IDENT GE number\n                     | IDENT EQ number\n                     | IDENT NE number\n    apply_stmt : APPLY IDENT ON target_list SEMICOLONmeasure_stmt : MEASURE target_list SEMICOLON\n    target_list : single_target target_tail\n    \n    target_tail : COMMA single_target target_tail\n                | empty\n    \n    single_target : qubit\n                  | IDENT WHERE condition_expr\n    qubit : IDENTqubit : IDENT LBRACKET INT RBRACKETqubit : IDENT LBRACKET STAR RBRACKETqubit : IDENT LBRACKET INT COLON INT RBRACKETgate_def : GATE IDENT LPAREN param_list RPAREN LBRACE statement_list RBRACEparam_list : IDENT param_tail\n    param_tail : COMMA IDENT param_tail\n               | empty\n    empty :'
    
_lr_action_items = {'CREATE':([0,3,4,5,6,7,22,40,70,71,75,],[8,8,-4,-5,-6,-7,-21,-20,8,-8,-31,]),'APPLY':([0,3,4,5,6,7,22,40,70,71,75,],[9,9,-4,-5,-6,-7,-21,-20,9,-8,-31,]),'MEASURE':([0,3,4,5,6,7,22,40,70,71,75,],[10,10,-4,-5,-6,-7,-21,-20,10,-8,-31,]),'GATE':([0,3,4,5,6,7,22,40,70,71,75,],[11,11,-4,-5,-6,-7,-21,-20,11,-8,-31,]),'$end':([1,2,3,4,5,6,7,12,22,40,71,75,],[0,-1,-3,-4,-5,-6,-7,-2,-21,-20,-8,-31,]),'RBRACE':([3,4,5,6,7,12,22,40,71,74,75,],[-3,-4,-5,-6,-7,-2,-21,-20,-8,75,-31,]),'QUBITS':([8,],[13,]),'IDENT':([9,10,11,13,21,24,26,28,48,49,54,],[14,18,19,20,18,18,32,37,32,32,69,]),'ON':([14,],[21,]),'SEMICOLON':([15,16,17,18,23,25,30,31,33,34,41,50,52,57,58,59,60,61,62,63,64,65,66,67,72,],[22,-35,-25,-27,-22,-24,40,-35,-26,-11,-23,-28,-29,71,-14,-12,-13,-15,-16,-17,-18,-19,-9,-10,-30,]),'COMMA':([16,17,18,31,33,34,37,50,52,58,59,60,61,62,63,64,65,66,67,69,72,],[24,-25,-27,24,-26,-11,54,-28,-29,-14,-12,-13,-15,-16,-17,-18,-19,-9,-10,54,-30,]),'WHERE':([18,],[26,]),'LBRACKET':([18,20,],[27,29,]),'LPAREN':([19,],[28,]),'INT':([27,29,42,43,44,45,46,47,51,],[35,39,59,59,59,59,59,59,68,]),'STAR':([27,],[36,]),'LT':([32,],[42,]),'GT':([32,],[43,]),'LE':([32,],[44,]),'GE':([32,],[45,]),'EQ':([32,],[46,]),'NE':([32,],[47,]),'AND':([33,34,58,59,60,61,62,63,64,65,66,67,],[48,-11,-14,-12,-13,-15,-16,-17,-18,-19,48,48,]),'OR':([33,34,58,59,60,61,62,63,64,65,66,67,],[49,-11,-14,-12,-13,-15,-16,-17,-18,-19,49,49,]),'RBRACKET':([35,36,39,68,],[50,52,57,72,]),'COLON':([35,],[51,]),'RPAREN':([37,38,53,55,69,73,],[-35,56,-32,-34,-35,-33,]),'FLOAT':([42,43,44,45,46,47,],[60,60,60,60,60,60,]),'LBRACE':([56,],[70,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,3,70,],[2,12,74,]),'statement':([0,3,70,],[3,3,3,]),'create_stmt':([0,3,70,],[4,4,4,]),'apply_stmt':([0,3,70,],[5,5,5,]),'measure_stmt':([0,3,70,],[6,6,6,]),'gate_def':([0,3,70,],[7,7,7,]),'target_list':([10,21,],[15,30,]),'single_target':([10,21,24,],[16,16,31,]),'qubit':([10,21,24,],[17,17,17,]),'target_tail':([16,31,],[23,41,]),'empty':([16,31,37,69,],[25,25,55,55,]),'condition_expr':([26,48,49,],[33,66,67,]),'simple_condition':([26,48,49,],[34,34,34,]),'param_list':([28,],[38,]),'param_tail':([37,69,],[53,73,]),'number':([42,43,44,45,46,47,],[58,61,62,63,64,65,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser.py',9),
  ('statement_list -> statement statement_list','statement_list',2,'p_statement_list','parser.py',14),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser.py',15),
  ('statement -> create_stmt','statement',1,'p_statement','parser.py',27),
  ('statement -> apply_stmt','statement',1,'p_statement','parser.py',28),
  ('statement -> measure_stmt','statement',1,'p_statement','parser.py',29),
  ('statement -> gate_def','statement',1,'p_statement','parser.py',30),
  ('create_stmt -> CREATE QUBITS IDENT LBRACKET INT RBRACKET SEMICOLON','create_stmt',7,'p_create_stmt','parser.py',38),
  ('condition_expr -> condition_expr AND condition_expr','condition_expr',3,'p_condition_expr','parser.py',64),
  ('condition_expr -> condition_expr OR condition_expr','condition_expr',3,'p_condition_expr','parser.py',65),
  ('condition_expr -> simple_condition','condition_expr',1,'p_condition_expr','parser.py',66),
  ('number -> INT','number',1,'p_number','parser.py',77),
  ('number -> FLOAT','number',1,'p_number','parser.py',78),
  ('simple_condition -> IDENT LT number','simple_condition',3,'p_simple_condition','parser.py',84),
  ('simple_condition -> IDENT GT number','simple_condition',3,'p_simple_condition','parser.py',85),
  ('simple_condition -> IDENT LE number','simple_condition',3,'p_simple_condition','parser.py',86),
  ('simple_condition -> IDENT GE number','simple_condition',3,'p_simple_condition','parser.py',87),
  ('simple_condition -> IDENT EQ number','simple_condition',3,'p_simple_condition','parser.py',88),
  ('simple_condition -> IDENT NE number','simple_condition',3,'p_simple_condition','parser.py',89),
  ('apply_stmt -> APPLY IDENT ON target_list SEMICOLON','apply_stmt',5,'p_apply_stmt','parser.py',120),
  ('measure_stmt -> MEASURE target_list SEMICOLON','measure_stmt',3,'p_measure_stmt','parser.py',127),
  ('target_list -> single_target target_tail','target_list',2,'p_target_list','parser.py',135),
  ('target_tail -> COMMA single_target target_tail','target_tail',3,'p_target_tail','parser.py',141),
  ('target_tail -> empty','target_tail',1,'p_target_tail','parser.py',142),
  ('single_target -> qubit','single_target',1,'p_single_target','parser.py',154),
  ('single_target -> IDENT WHERE condition_expr','single_target',3,'p_single_target','parser.py',155),
  ('qubit -> IDENT','qubit',1,'p_qubit_param','parser.py',165),
  ('qubit -> IDENT LBRACKET INT RBRACKET','qubit',4,'p_qubit_index','parser.py',169),
  ('qubit -> IDENT LBRACKET STAR RBRACKET','qubit',4,'p_qubit_star','parser.py',173),
  ('qubit -> IDENT LBRACKET INT COLON INT RBRACKET','qubit',6,'p_qubit_range','parser.py',177),
  ('gate_def -> GATE IDENT LPAREN param_list RPAREN LBRACE statement_list RBRACE','gate_def',8,'p_gate_def','parser.py',181),
  ('param_list -> IDENT param_tail','param_list',2,'p_param_list','parser.py',185),
  ('param_tail -> COMMA IDENT param_tail','param_tail',3,'p_param_tail','parser.py',190),
  ('param_tail -> empty','param_tail',1,'p_param_tail','parser.py',191),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',199),
]
