from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
import math

a = QuantumRegister(4, "a")
b = QuantumRegister(4, "b")
cin = QuantumRegister(1, "cin")
cout = QuantumRegister(1, "cout")
a_c = ClassicalRegister(4, "a_c")
b_c = ClassicalRegister(4, "b_c")
cin_c = ClassicalRegister(1, "cin_c")
cout_c = ClassicalRegister(1, "cout_c")
qc = QuantumCircuit(a, b, cin, cout, a_c, b_c, cin_c, cout_c)
qc.x(a[0])
qc.x(b[0])
qc.cx(a[0], b[0])
qc.cx(a[0], cin[0])
qc.ccx(cin[0], b[0], a[0])
qc.cx(a[1], b[1])
qc.cx(a[2], b[2])
qc.cx(a[3], b[3])
qc.cx(a[1], a[0])
qc.cx(a[2], a[1])
qc.cx(a[3], a[2])
qc.ccx(a[0], b[1], a[1])
qc.ccx(a[1], b[2], a[2])
qc.ccx(a[2], b[3], a[3])
qc.cx(a[3], cout[0])
qc.ccx(a[2], b[1], a[1])
qc.ccx(a[1], b[2], a[2])
qc.ccx(a[0], b[3], a[3])
qc.cx(a[1], a[2])
qc.cx(a[2], a[1])
qc.cx(a[3], a[0])
qc.cx(a[2], b[1])
qc.cx(a[1], b[2])
qc.cx(a[0], b[3])
qc.ccx(cin[0], b[0], a[0])
qc.cx(a[0], cin[0])
qc.cx(cin[0], b[0])
qc.measure(a, a_c)
qc.measure(b, b_c)