from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
import math

q = QuantumRegister(2, "q")
anc = QuantumRegister(1, "anc")
q_c = ClassicalRegister(2, "q_c")
anc_c = ClassicalRegister(1, "anc_c")
qc = QuantumCircuit(q, anc, q_c, anc_c)
qc.h(q[0])
qc.h(q[1])
qc.x(anc[0])
qc.h(anc[0])
qc.ccx(q[0], q[1], anc[0])
qc.h(q[0])
qc.h(q[1])
qc.x(q[0])
qc.x(q[1])
qc.h(q[1])
qc.cx(q[0], q[1])
qc.h(q[1])
qc.x(q[0])
qc.x(q[1])
qc.h(q[0])
qc.h(q[1])
qc.measure(q, q_c)