from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter
import math

A = Parameter("A")
B = Parameter("B")

q = QuantumRegister(8, "q")
c = ClassicalRegister(8, "c")
q_c = ClassicalRegister(8, "q_c")
qc = QuantumCircuit(q, c, q_c)
qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.x(q[4])
qc.x(q[5])
qc.x(q[6])
qc.x(q[7])
qc.z(q[0])
qc.z(q[3])
qc.z(q[6])
qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.cx(q[0], q[4])
qc.cx(q[1], q[5])
qc.cx(q[2], q[6])
qc.cx(q[3], q[7])
qc.measure(q[0], c[0])
qc.measure(q[1], c[1])
qc.measure(q[2], c[2])
qc.measure(q[3], c[3])
qc.measure(q[4], c[4])
qc.measure(q[5], c[5])
qc.measure(q[6], c[6])
qc.measure(q[7], c[7])