from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter
import math

q = QuantumRegister(6, "q")
q_c = ClassicalRegister(6, "q_c")
qc = QuantumCircuit(q, q_c)
qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.h(q[4])
qc.h(q[5])
qc.x(q[0])
qc.x(q[1])
qc.x(q[2])
qc.y(q[3])
qc.y(q[4])
qc.y(q[5])
qc.z(q[3])
qc.z(q[2])
qc.z(q[1])
qc.x(q[1])
qc.x(q[2])
qc.swap(q[5], q[0])
qc.swap(q[4], q[1])
qc.swap(q[3], q[2])
qc.swap(q[2], q[3])
qc.swap(q[1], q[4])
qc.measure(q, q_c)