from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
import math

q = QuantumRegister(4, "q")
oracle = QuantumRegister(1, "oracle")
q_c = ClassicalRegister(4, "q_c")
oracle_c = ClassicalRegister(1, "oracle_c")
qc = QuantumCircuit(q, oracle, q_c, oracle_c)
qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.z(q[0])
qc.z(q[1])
qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.x(q[0])
qc.x(q[1])
qc.x(q[2])
qc.x(q[3])
qc.h(q[3])
qc.x(q[0])
qc.x(q[1])
qc.x(q[2])
qc.h(q[3])
qc.x(q[0])
qc.x(q[1])
qc.x(q[2])
qc.x(q[3])
qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.measure(q, q_c)