from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
import math

q = QuantumRegister(4, "q")
anc = QuantumRegister(3, "anc")
q_c = ClassicalRegister(4, "q_c")
anc_c = ClassicalRegister(3, "anc_c")
measure_bit = ClassicalRegister(1, "measure_bit")
qc = QuantumCircuit(q, anc, q_c, anc_c, measure_bit)
qc.h(q[0])
qc.rx(1.5707963268, q[1])
qc.rz(3.1415926536, q[2])
qc.h(q[0])
qc.h(q[2])
qc.h(q[0])
qc.cx(q[0], anc[0])
qc.cx(q[0], anc[0])
qc.cx(q[1], anc[1])
qc.cx(q[2], anc[2])
qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.measure(anc[0], measure_bit[0])